#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
# Config: jozef@jozef-mbp
#

# Load ~/.exports, ~/.extra
for file in ~/.{exports,extra}; do
  [ -r "$file" ] && source "$file"
done
unset file

export GITHUB_USER="jozefizso"
