#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
# Config: jozef@jozef-mbp
#

#
# Paths
#

# preload PATH in Mac OS X
if [ -x /usr/libexec/path_helper ]; then
  # we must clear PATH variable (http://www.softec.lu/site/DevelopersCorner/MasteringThePathHelper)
  PATH=''
  eval `/usr/libexec/path_helper -s`
fi

# load paths defined in .paths file
if [ -f ~/.paths ]; then
  local userpath=$(cat ~/.paths | tr \\n ':')
  export PATH="$userpath:$PATH"
fi

typeset -gU cdpath fpath mailpath path


#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='subl -w'
export VISUAL='subl -w'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
if (( $+commands[lesspipe.sh] )); then
  export LESSOPEN='| /usr/bin/env lesspipe.sh %s 2>&-'
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$USER"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"
if [[ ! -d "$TMPPREFIX" ]]; then
  mkdir -p "$TMPPREFIX"
fi

